import React from 'react'
import TopBanner from '../components/Common/Banner/TopBanner'

const PrivacyPolicy = () => {
    const BannerContainerData = {
      BannerHeading: "PriVacy Policy",
      BannerParagraph: "India's premier processed food manufacturers, offering manufacturing and packing services to well-known multinational corporations."
    }
    const bannerImage = 'https://images.pexels.com/photos/1043458/pexels-photo-1043458.jpeg'
  return (
    <main className="flex min-h-screen flex-col items-cente">
        <TopBanner bannerImage={bannerImage} BannerContainerData={BannerContainerData} />
        <div className='w-full relative py-8 max-w-[1280px] mx-auto bg-white my-16 rounded-xl px-8'>
        <div className="py-20"><h1 className="block p text-5xl mb-5" id="privacy-policy">Privacy Policy</h1>
            <p className="block p text-lg mb-4 text-base-content/80 leading-8">Effective date: September 01, 2021</p>
            
            <p className="block p text-lg mb-4 text-base-content/80 leading-8">JS Template ("us", "we", or "our") operates the https://jstemplate.net website (hereinafter referred to as the "Service").</p>
            
            <p className="block p text-lg mb-4 text-base-content/80 leading-8">This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
            
            <p className="block p text-lg mb-4 text-base-content/80 leading-8">We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.</p>
            
            <h2 className="block p text-4xl mb-5" id="definitions">Definitions</h2>
            <ul className="list-disc list-inside my-4">
                <li className="mb-2 last-of-type:mb-0">
                    <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>Service</strong></p>
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8">Service is the https://jstemplate.net website operated by JS Template</p>
                            </li>
                            <li className="mb-2 last-of-type:mb-0">
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>Personal Data</strong></p>
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                            </li>
                            <li className="mb-2 last-of-type:mb-0">
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>Usage Data</strong></p>
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                            </li>
                            <li className="mb-2 last-of-type:mb-0">
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>Cookies</strong></p>
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8">Cookies are small files stored on your device (computer or mobile device).</p>
                            </li>
                            </ul>
                            
                            <h2 className="block p text-4xl mb-5" id="information-collection-and-use">Information Collection and Use</h2>
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8">We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                            <h3 className="block p text-3xl mb-4" id="types-of-data-collected">Types of Data Collected</h3>
                            <h4 className="block p text-2xl mb-4" id="personal-data">Personal Data</h4>
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
                            <ul className="list-disc list-inside my-4">
                            <li className="mb-2 last-of-type:mb-0">Email address</li><li className="mb-2 last-of-type:mb-0">First name and last name</li><li className="mb-2 last-of-type:mb-0">Phone number</li><li className="mb-2 last-of-type:mb-0">Address, State, Province, ZIP/Postal code, City</li><li className="mb-2 last-of-type:mb-0">Cookies and Usage Data</li>
                            </ul>
                            <p className="block p text-lg mb-4 text-base-content/80 leading-8">We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>
                            <h4 className="block p text-2xl mb-4" id="usage-data">Usage Data</h4>
                                
                                <p className="block p text-lg mb-4 text-base-content/80 leading-8">When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data ("Usage Data").</p>
                                <h4 className="block p text-2xl mb-4" id="tracking-&amp;-cookies-data">Tracking &amp; Cookies Data</h4>
                                <p className="block p text-lg mb-4 text-base-content/80 leading-8">We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
                                <p className="block p text-lg mb-4 text-base-content/80 leading-8">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device.</p>
                                <p className="block p text-lg mb-4 text-base-content/80 leading-8">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                                <p className="block p text-lg mb-4 text-base-content/80 leading-8">Examples of Cookies we use:</p>
                                <ul className="list-disc list-inside my-4">
                                <li className="mb-2 last-of-type:mb-0"><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
                                <li className="mb-2 last-of-type:mb-0"><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                                <li className="mb-2 last-of-type:mb-0"><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
                                </ul>
                                <h2 className="block p text-4xl mb-5" id="use-of-data">Use of Data</h2>
                                <p className="block p text-lg mb-4 text-base-content/80 leading-8">JS Template uses the collected data for various purposes:</p>
                                <ul className="list-disc list-inside my-4">
                                <li className="mb-2 last-of-type:mb-0">To provide and maintain our Service</li>
                                    <li className="mb-2 last-of-type:mb-0">To notify you about changes to our Service</li>
                                    <li className="mb-2 last-of-type:mb-0">To allow you to participate in interactive features of our Service when you choose to do so</li>
                                    <li className="mb-2 last-of-type:mb-0">To provide customer support</li>
                                    <li className="mb-2 last-of-type:mb-0">To gather analysis or valuable information so that we can improve our Service</li>
                                    <li className="mb-2 last-of-type:mb-0">To monitor the usage of our Service</li>
                                    <li className="mb-2 last-of-type:mb-0">To detect, prevent and address technical issues</li>
                                    <li className="mb-2 last-of-type:mb-0">To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                                    </ul>
                                    <h2 className="block p text-4xl mb-5" id="retention-of-data">Retention of Data</h2>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">JS Template will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.</p>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">JS Template will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>
                                    <h2 className="block p text-4xl mb-5" id="transfer-of-data">Transfer of Data</h2>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">If you are located outside Bangladesh and choose to provide information to us, please note that we transfer the data, including Personal Data, to Bangladesh and process it there.</p>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">JS Template will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
                                    <h2 className="block p text-4xl mb-5" id="disclosure-of-data">Disclosure of Data</h2>
                                    <h3 className="block p text-3xl mb-4" id="business-transaction">Business Transaction</h3>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">If JS Template is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                                    <h3 className="block p text-3xl mb-4" id="disclosure-for-law-enforcement">Disclosure for Law Enforcement</h3>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">Under certain circumstances, JS Template may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                                    <h3 className="block p text-3xl mb-4" id="legal-requirements">Legal Requirements</h3>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">JS Template may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
                                    <ul className="list-disc list-inside my-4">
                                    <li className="mb-2 last-of-type:mb-0">To comply with a legal obligation</li>
                                    <li className="mb-2 last-of-type:mb-0">To protect and defend the rights or property of JS Template</li>
                                    <li className="mb-2 last-of-type:mb-0">To prevent or investigate possible wrongdoing in connection with the Service</li>
                                    <li className="mb-2 last-of-type:mb-0">To protect the personal safety of users of the Service or the public</li>
                                    <li className="mb-2 last-of-type:mb-0">To protect against legal liability</li>
                                    </ul>
                                    <h2 className="block p text-4xl mb-5" id="security-of-data">Security of Data</h2>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
                                    <h2 className="block p text-4xl mb-5" id="our-policy-on-&quot;do-not-track&quot;-signals-under-the-california-online-protection-act-(caloppa)">Our Policy on "Do Not Track" Signals under the California Online Protection Act (CalOPPA)</h2>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
                                    <h2 className="block p text-4xl mb-5" id="your-data-protection-rights-under-the-general-data-protection-regulation-(gdpr)">Your Data Protection Rights under the General Data Protection Regulation (GDPR)</h2>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.</p>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">We aim to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.</p>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">In certain circumstances, you have the following data protection rights:</p>
                                    <ul className="list-disc list-inside my-4">
                                    <li className="mb-2 last-of-type:mb-0">
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>the right to access, update or to delete the information we have on you;</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you. This also enables you to receive a copy of the Personal Data we hold about you.</p>
                                    </li>
                                    <li className="mb-2 last-of-type:mb-0">
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>the right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
                                    </li>
                                    <li className="mb-2 last-of-type:mb-0">
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>the right to object.</strong> You have the right to object to our processing of your Personal Data.</p>
                                    </li>
                                    <li className="mb-2 last-of-type:mb-0">
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>the right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</p>
                                    </li>
                                    <li className="mb-2 last-of-type:mb-0">
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>the right to data portability.</strong> You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format.</p>
                                    </li>
                                    <li className="mb-2 last-of-type:mb-0">
                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8"><strong>the right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information.</p>
                                    </li>
                                    </ul>

                                    <p className="block p text-lg mb-4 text-base-content/80 leading-8">Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.</p></div>
        </div>
    </main>
  )
}

export default PrivacyPolicy